### ISSUE TITLE
Current master branch fails with `token_id` key not found

### ISSUE THREAD

**Issue by axsaucedo** [SeldonIO/seldon-deploy-sdk#39]
It seems when installing from master and running through the example, there is an issue with some 2nd+ level dependency that may have been updated, resulting in the basic auth workfow (eg the one in the readme) no longer working.

**Comment by adriangonz** [comment]
After having a deeper look into this, it seems that some OIDC providers (e.g. Azure AD) will just not return an `id_token` when using the `client_credentials` flow. This is by design, as that flow is not meant to authenticate an "user", thus doesn't need an `id_token`. 

However, in these cases, there should still be an `access_token` available on the payload, which seems to be accepted by Seldon Deploy. Therefore, it would be good to fallback to `access_token` when using the `client_credentials` flow and the `id_token` is missing on the payload.
