### ISSUE TITLE
Rename the github repo to match the pip package name

### ISSUE THREAD

**Issue by FarrandTom** [SeldonIO/seldon-deploy-sdk#4]
It would be good if we could rename the git repository to match up with the pip package name so that is more easily indexed and found via Google. 

Furthermore, if we could add a link to this Git repository in the PyPi page it would make usage of the package simpler if someone just stumbles across the PyPi page.

**Comment by axsaucedo** [comment]
+1 - I sometimes get confused when not finding the "-sdk"

@adriangonz if I update the name would anything break (CI, scripts, etc)?

**Comment by adriangonz** [comment]
I can't see any references to `seldon-deploy-client` so I think it should be alright to go ahead @axsaucedo!

**Comment by axsaucedo** [comment]
Sounds good - just updated

**Comment by axsaucedo** [comment]
Actually @adriangonz there may be references in the documentation that would still reference "-client" instead of "sdk - there is a redirect set up so this shouldn't be an issue, but we should still make sure it's updated (would only be an issue if we crete another repo called "seldon-deploy-client"
